server:
  port: 8081

spring:
  datasource:
    username: root
    password: ufcr28BC
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 128000KB
      max-request-size: 128000KB